# Icon
favicon: /favicon.ico
# SEO
keywords: Hexo, Gruntjs, Nodejs, Reactjs, Vuejs
# Header
page_background: http://callfiles.ueibo.com/hexo-theme-laughing/page_background.jpg
page_menu_button: dark
post_background: http://callfiles.ueibo.com/hexo-theme-laughing/post_background.jpg
post_menu_button: light
title_plancehold: 随笔
author:
  head: http://callfiles.ueibo.com/hexo-theme-laughing/thumb.jpg
  signature: Only when you plant the flowers can you really smell their fragrance.
navication:
  - name: Github
    link: https://github.com
  - name: V2EX
    link: https://www.v2ex.com/
# content
content_width: 800
# Footer
## Social icon list: [facebook, twitter, weibo, wechat, github, stackoverflow, linkin, email, segmentfault, flickr]
social:
  - name: GitHub
    icon: github
    link: https://github.com/BoizZ
  - name: Weibo
    icon: weibo
    link: https://weibo.com/heqibang
  - name: SegmentFault
    icon: segmentfault
    link: https://www.segmentfault.com/u/bon
# Duoshuo
duoshuo:
  enable: true
  siteName: ueibo
# Copyright
copyright:
  record: false
  hexo: true
  laughing: true